spring:
  datasource:
    url: jdbc:mysql://sopkathon-web2-rds.c5my4geuwqnk.ap-northeast-2.rds.amazonaws.com:3306/sopkathon_web2
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  web:
    resources:
      add-mappings: false # Disable static resource mapping (For NoHandlerFoundException)

aws:
  region: ap-northeast-2
  s3:
    bucket: ${S3_BUCKET_NAME}

client:
  invite-base-url: ${CLIENT_INVITE_BASE_URL:http://localhost:5173}
